### ISSUE TITLE
`price_gross` is missing

### ISSUE THREAD

**Issue by soerface** [flxai/hetzner-fix-report#1]
To be able to display an accurate price, I need the VAT or gross price in the CSV file. In the pdf there are three entries at the end of the document, net price, VAT, and gross price.

Btw, the column `price_netto` should be called `price_net`, the former is german.

**Comment by flxai** [comment]
CSV now contains `vat` (e.g. `0.19`), and [calculates](https://github.com/flxai/hetzner-fix-report/commit/2e21072bdb4339f4745b6677358bedc463f934dc#diff-2d4e9abcd7505e8f5a1d8855d4a74995R101) `price_gross` for each item. I am uncertain as to whether this introduces rounding errors, so please check this.

I also renamed `price_netto` to `price_net`. Thanks for the hint.
